Add option use to use a saved profile

diff --git a/gitprofile b/gitprofile
--- a/gitprofile
+++ b/gitprofile
@@ -13,7 +13,8 @@ print_help() {
   -s --save:\t\tsave the current profile\n \
   -n --new:\t\tadd a new profile\n \
   -l --list:\t\tlist saved profile\n \
-  -d --delete:\t\tdelete one profile\n\n \
+  -d --delete:\t\tdelete one profile\n \
+  -u --use\t\tuse one profile saved\n\n \
   --log:\t\toption based on git log\n \
      -l --list:\tlist commiter profile in project\n \
      -u --use:\t\tuse commiter profile\n\n \
@@ -239,6 +240,41 @@ case $1 in
               add_profile "$profile"
             fi
           done
+        fi
+      ;;
+      -u | --use)
+        trap 'interrupt "Profile not changed" ' INT
+         if [ -e "$FILE" ]; then
+          listProfile=$(cat "$FILE" | tr '\n' ';' | cut -c 2- | rev | cut -c 2- | rev)
+        else
+          listProfile=""
+        fi
+        if [ -z "$listProfile" ]; then
+          echo -e "No profile saved"
+        else
+          print_list_profile "$listProfile"
+          while [ 1 ]
+          do
+            read -p "Choice profile: " idC
+            if [[ $idC =~ ^[0-9]+$ ]] && [ $idC -ne 0 ] && [ $idC -le $id ]; then
+              break
+            else
+              echo -e "Invalid id"
+            fi
+          done
+          i=$(($idC - 1))
+          profiles=($listProfile)
+          IFS=':' read -a p <<< "${profiles[$i]}"
+          print_profile ${p[0]} ${p[1]}
+          read -p "Configure with this profile (yes/no)? " choice
+          if [ "$choice" = "yes" ] || [ "$choice" = "y" ]; then
+            $GIT config user.name ${p[0]}
+            $GIT config user.email ${p[1]}
+            echo -e "Profile changed in: "
+            print_profile ${p[0]} ${p[1]}
+          else
+            interrupt "Profile not changed"
+          fi
         fi
       ;;
       "")
